# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/TUT5_bd/TUT5_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd || ORIG_REF_NAME==TUT5_bd} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_microblaze_0_0/TUT5_bd_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_microblaze_0_0 || ORIG_REF_NAME==TUT5_bd_microblaze_0_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_dlmb_v10_0 || ORIG_REF_NAME==TUT5_bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_ilmb_v10_0/TUT5_bd_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_ilmb_v10_0 || ORIG_REF_NAME==TUT5_bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_dlmb_bram_if_cntlr_0/TUT5_bd_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TUT5_bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_ilmb_bram_if_cntlr_0/TUT5_bd_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TUT5_bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_lmb_bram_0/TUT5_bd_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_lmb_bram_0 || ORIG_REF_NAME==TUT5_bd_lmb_bram_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_xbar_0/TUT5_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_xbar_0 || ORIG_REF_NAME==TUT5_bd_xbar_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_microblaze_0_axi_periph_0/TUT5_bd_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TUT5_bd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_microblaze_0_axi_intc_0/TUT5_bd_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TUT5_bd_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_microblaze_0_xlconcat_0/TUT5_bd_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_microblaze_0_xlconcat_0 || ORIG_REF_NAME==TUT5_bd_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_mdm_1_0/TUT5_bd_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_mdm_1_0 || ORIG_REF_NAME==TUT5_bd_mdm_1_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_clk_wiz_1_0/TUT5_bd_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_clk_wiz_1_0 || ORIG_REF_NAME==TUT5_bd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_rst_clk_wiz_1_100M_0/TUT5_bd_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TUT5_bd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_mig_7series_0_1/TUT5_bd_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_mig_7series_0_1 || ORIG_REF_NAME==TUT5_bd_mig_7series_0_1} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_mii_to_rmii_0_1/TUT5_bd_mii_to_rmii_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_mii_to_rmii_0_1 || ORIG_REF_NAME==TUT5_bd_mii_to_rmii_0_1} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_axi_uartlite_0_1/TUT5_bd_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_axi_uartlite_0_1 || ORIG_REF_NAME==TUT5_bd_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_axi_ethernetlite_0_0/TUT5_bd_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_axi_ethernetlite_0_0 || ORIG_REF_NAME==TUT5_bd_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_axi_timer_0_1/TUT5_bd_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_axi_timer_0_1 || ORIG_REF_NAME==TUT5_bd_axi_timer_0_1} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/TUT5_bd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_axi_smc_0 || ORIG_REF_NAME==TUT5_bd_axi_smc_0} -quiet] -quiet

# IP: bd/TUT5_bd/ip/TUT5_bd_rst_mig_7series_0_81M_0/TUT5_bd_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TUT5_bd_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==TUT5_bd_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: bd/TUT5_bd/TUT5_bd_ooc.xdc
