# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Liza_TUT5/Liza_TUT5.cache/wt [current_project]
set_property parent.project_path C:/Liza_TUT5/Liza_TUT5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Liza_TUT5/Liza_TUT5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/hdl/TUT5_bd_wrapper.v
add_files C:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/TUT5_bd.bd
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_microblaze_0_0/TUT5_bd_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_microblaze_0_0/TUT5_bd_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_microblaze_0_0/TUT5_bd_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_ilmb_v10_0/TUT5_bd_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_ilmb_v10_0/TUT5_bd_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_bram_if_cntlr_0/TUT5_bd_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_ilmb_bram_if_cntlr_0/TUT5_bd_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_lmb_bram_0/TUT5_bd_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_xbar_0/TUT5_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_microblaze_0_axi_intc_0/TUT5_bd_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_microblaze_0_axi_intc_0/TUT5_bd_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_microblaze_0_axi_intc_0/TUT5_bd_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mdm_1_0/TUT5_bd_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mdm_1_0/TUT5_bd_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_clk_wiz_1_0/TUT5_bd_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_clk_wiz_1_0/TUT5_bd_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_clk_wiz_1_0/TUT5_bd_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_rst_clk_wiz_1_100M_0/TUT5_bd_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_rst_clk_wiz_1_100M_0/TUT5_bd_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_rst_clk_wiz_1_100M_0/TUT5_bd_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mig_7series_0_1/TUT5_bd_mig_7series_0_1/user_design/constraints/TUT5_bd_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mig_7series_0_1/TUT5_bd_mig_7series_0_1/user_design/constraints/TUT5_bd_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mig_7series_0_1/TUT5_bd_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mii_to_rmii_0_1/TUT5_bd_mii_to_rmii_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_mii_to_rmii_0_1/TUT5_bd_mii_to_rmii_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_uartlite_0_1/TUT5_bd_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_uartlite_0_1/TUT5_bd_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_uartlite_0_1/TUT5_bd_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_ethernetlite_0_0/TUT5_bd_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_ethernetlite_0_0/TUT5_bd_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_ethernetlite_0_0/TUT5_bd_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_ethernetlite_0_0/TUT5_bd_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_timer_0_1/TUT5_bd_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_timer_0_1/TUT5_bd_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_1/bd_c913_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_1/bd_c913_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_2/bd_c913_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_2/bd_c913_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_3/bd_c913_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_3/bd_c913_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_4/bd_c913_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_5/bd_c913_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_6/bd_c913_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_7/bd_c913_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_8/bd_c913_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_12/bd_c913_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_13/bd_c913_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_14/bd_c913_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_15/bd_c913_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_16/bd_c913_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_17/bd_c913_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_21/bd_c913_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_22/bd_c913_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_23/bd_c913_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_24/bd_c913_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_25/bd_c913_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_26/bd_c913_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_27/bd_c913_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_28/bd_c913_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/bd_0/ip/ip_29/bd_c913_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_rst_mig_7series_0_81M_0/TUT5_bd_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_rst_mig_7series_0_81M_0/TUT5_bd_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_rst_mig_7series_0_81M_0/TUT5_bd_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/TUT5_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Liza_TUT5/Liza_TUT5.srcs/constrs_1/new/eth_ref_clk.xdc
set_property used_in_implementation false [get_files C:/Liza_TUT5/Liza_TUT5.srcs/constrs_1/new/eth_ref_clk.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TUT5_bd_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TUT5_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TUT5_bd_wrapper_utilization_synth.rpt -pb TUT5_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
