# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0.xci
# IP: The module: 'TUT5_bd_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TUT5_bd_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TUT5_bd_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0.xci
# IP: The module: 'TUT5_bd_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TUT5_bd_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Liza_TUT5/Liza_TUT5.srcs/sources_1/bd/TUT5_bd/ip/TUT5_bd_dlmb_v10_0/TUT5_bd_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TUT5_bd_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
