webtalk_init -webtalk_dir C:\\Users\\zoubakin\\warmup_group\\warmup_group.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-01-25 15:28:08" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111048_179741397_210699440_801" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d81da57um08rt0j7p47jl9a5m1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.081 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1643139661820" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3.1" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1643139661820"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1643142488229"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1643142488229"
webtalk_transmit -clientid 814159290 -regid "174111048_179741397_210699440_801" -xml C:\\Users\\zoubakin\\warmup_group\\warmup_group.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\zoubakin\\warmup_group\\warmup_group.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\zoubakin\\warmup_group\\warmup_group.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
